# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_driver.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDriver(object):
    def setupUi(self, AddDriver):
        AddDriver.setObjectName("AddDriver")
        AddDriver.resize(607, 289)
        AddDriver.setStyleSheet("#form{\n"
"background:url(img/pbg4.jpg)\n"
"}\n"
"QFrame{\n"
"background: rgba(0,0,0,0.7);\n"
"border-radius:15px;\n"
"}\n"
"QLineEdit{\n"
"background:transparent;\n"
"border:2px solid #2312ff;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"QLineEdit:focus{\n"
"background:transparent;\n"
"border:2px solid red;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"QPushButton{\n"
"border-radius:15px;\n"
"color:white;\n"
"border:2px solid #2312ff;\n"
"background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"QLabel{\n"
"color:white;\n"
"background:transparent;\n"
"\n"
"}\n"
"\n"
"")
        self.form = QtWidgets.QWidget(AddDriver)
        self.form.setObjectName("form")
        self.frame = QtWidgets.QFrame(self.form)
        self.frame.setGeometry(QtCore.QRect(30, 30, 551, 241))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.add_driver_passport = QtWidgets.QLineEdit(self.frame)
        self.add_driver_passport.setGeometry(QtCore.QRect(30, 80, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.add_driver_passport.setFont(font)
        self.add_driver_passport.setAlignment(QtCore.Qt.AlignCenter)
        self.add_driver_passport.setObjectName("add_driver_passport")
        self.passport_lbl = QtWidgets.QLabel(self.frame)
        self.passport_lbl.setGeometry(QtCore.QRect(280, 80, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.passport_lbl.setFont(font)
        self.passport_lbl.setObjectName("passport_lbl")
        self.add_driver_btn = QtWidgets.QPushButton(self.frame)
        self.add_driver_btn.setGeometry(QtCore.QRect(180, 170, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.add_driver_btn.setFont(font)
        self.add_driver_btn.setObjectName("add_driver_btn")
        AddDriver.setCentralWidget(self.form)

        self.retranslateUi(AddDriver)
        QtCore.QMetaObject.connectSlotsByName(AddDriver)

    def retranslateUi(self, AddDriver):
        _translate = QtCore.QCoreApplication.translate
        AddDriver.setWindowTitle(_translate("AddDriver", "Add driver"))
        self.passport_lbl.setText(_translate("AddDriver", "Серия и номер паспорта"))
        self.add_driver_btn.setText(_translate("AddDriver", "Добавить водителя"))
