# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'case_pay.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CasePay(object):
    def setupUi(self, CasePay):
        CasePay.setObjectName("CasePay")
        CasePay.resize(800, 600)
        CasePay.setStyleSheet("\n"
"#form{\n"
"background:url(img/pbg4.jpg)\n"
"}\n"
"#comp_message{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"#choose_person_lbl{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"#choose_case_lbl{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"#complain{\n"
"border-radius:15px;\n"
"color:white;\n"
"border:2px solid #2312ff;\n"
"background:transparent;\n"
"}\n"
"#find_complaint{\n"
"border-radius:15px;\n"
"color:white;\n"
"border:2px solid #2312ff;\n"
"background:transparent;\n"
"}\n"
"#find_complaint:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#complain:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#case_fine_pay:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#complain:disabled{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"QTextEdit{\n"
"background: transparent;\n"
"border-radius:15px;\n"
"color:white\n"
"}\n"
"QFrame{\n"
"background: rgba(0,0,0,0.7);\n"
"border-radius:15px;\n"
"}\n"
"#pay_frame_1{\n"
"background: rgba(0,0,0,0.7);\n"
"border-radius:15px;\n"
"}\n"
"#pay_frame_2{\n"
"background: rgba(0,0,0,0.7);\n"
"border-radius:15px;\n"
"}\n"
"QComboBox{\n"
"border:1px solid #2312ff;\n"
"border-radius:4px;\n"
"padding-left: 10px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"}\n"
"QComboBox:on{\n"
"border:2px solid #2312ff;\n"
"}\n"
"QComboBox QListView{\n"
"font-size:12px;\n"
"border: 1px solid rgba(0,0,0,10%);\n"
"padding: 5px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"outline:0px;\n"
"}\n"
"QComboBox QListView::item{\n"
"pading-left:10px;\n"
"background-color:rgba(0,0,0,0.7);\n"
"}\n"
"QComboBox QListView::item:hover{\n"
"background-color:#1e90ff;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"background-color:#1e90ff;\n"
"}\n"
"#sum_fine_pay{\n"
"border-radius:15px;\n"
"color:white;\n"
"border:2px solid #2312ff;\n"
"background:transparent;\n"
"}\n"
"#case_fine_pay{\n"
"border-radius:15px;\n"
"color:white;\n"
"border:2px solid #2312ff;\n"
"background:transparent;\n"
"}\n"
"#sum_fine_pay:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#case_fine_pay:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#add_person{\n"
"border-radius:4px;\n"
"color:white;\n"
"background:rgb(0,128,0);\n"
"}\n"
"#delete_person{\n"
"border-radius:4px;\n"
"color:white;\n"
"background:rgb(130,0,2);\n"
"}\n"
"#sum_fine_lbl{\n"
"color:white;\n"
"border:4px solid blue;\n"
"border-radius:15px;\n"
"}\n"
"#case_fine_lbl{\n"
"color:white;\n"
"border:4px solid blue;\n"
"border-radius:15px;\n"
"}\n"
"QLabel{\n"
"color:white;\n"
"\n"
"}\n"
"#sum_fine_value{\n"
"color:white;\n"
"border:2px solid blue;\n"
"border-radius:15px;\n"
"}\n"
"#case_fine_value{\n"
"color:white;\n"
"border:2px solid blue;\n"
"border-radius:15px;\n"
"}\n"
"#sum_fine_pay:disabled{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#case_fine_pay:disabled{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#back{\n"
"border-radius:15px;\n"
"color:white;\n"
"border:2px solid #fff;\n"
"background:transparent;\n"
"}\n"
"#back:hover{\n"
"border-radius:15px;\n"
"border:2px solid rgb(200, 0 ,8);\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#del_acc{\n"
"border-radius:15px;\n"
"color:white;\n"
"border:2px solid #fff;\n"
"background:transparent;\n"
"}\n"
"#del_acc:hover{\n"
"border-radius:15px;\n"
"border:2px solid rgb(200, 0 ,8);\n"
"color:white;\n"
"background: transparent;\n"
"}")
        self.form = QtWidgets.QWidget(CasePay)
        self.form.setObjectName("form")
        self.cb_person = QtWidgets.QComboBox(self.form)
        self.cb_person.setGeometry(QtCore.QRect(10, 30, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.cb_person.setFont(font)
        self.cb_person.setObjectName("cb_person")
        self.choose_person_lbl = QtWidgets.QLabel(self.form)
        self.choose_person_lbl.setGeometry(QtCore.QRect(10, 10, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.choose_person_lbl.setFont(font)
        self.choose_person_lbl.setObjectName("choose_person_lbl")
        self.cb_case = QtWidgets.QComboBox(self.form)
        self.cb_case.setGeometry(QtCore.QRect(10, 91, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.cb_case.setFont(font)
        self.cb_case.setObjectName("cb_case")
        self.case_frame = QtWidgets.QFrame(self.form)
        self.case_frame.setGeometry(QtCore.QRect(10, 140, 371, 401))
        self.case_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.case_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.case_frame.setObjectName("case_frame")
        self.case_te = QtWidgets.QTextEdit(self.case_frame)
        self.case_te.setGeometry(QtCore.QRect(10, 20, 351, 371))
        self.case_te.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.case_te.setReadOnly(True)
        self.case_te.setPlaceholderText("......")
        self.case_te.setObjectName("case_te")
        self.pay_frame_1 = QtWidgets.QFrame(self.form)
        self.pay_frame_1.setGeometry(QtCore.QRect(430, 30, 361, 171))
        self.pay_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pay_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pay_frame_1.setObjectName("pay_frame_1")
        self.sum_fine_lbl = QtWidgets.QLabel(self.pay_frame_1)
        self.sum_fine_lbl.setGeometry(QtCore.QRect(10, 10, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.sum_fine_lbl.setFont(font)
        self.sum_fine_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.sum_fine_lbl.setObjectName("sum_fine_lbl")
        self.sum_fine_value = QtWidgets.QLabel(self.pay_frame_1)
        self.sum_fine_value.setGeometry(QtCore.QRect(10, 110, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.sum_fine_value.setFont(font)
        self.sum_fine_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sum_fine_value.setObjectName("sum_fine_value")
        self.sum_fine_pay = QtWidgets.QPushButton(self.pay_frame_1)
        self.sum_fine_pay.setGeometry(QtCore.QRect(200, 110, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.sum_fine_pay.setFont(font)
        self.sum_fine_pay.setObjectName("sum_fine_pay")
        self.pay_frame_2 = QtWidgets.QFrame(self.form)
        self.pay_frame_2.setGeometry(QtCore.QRect(430, 210, 361, 181))
        self.pay_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pay_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pay_frame_2.setObjectName("pay_frame_2")
        self.case_fine_pay = QtWidgets.QPushButton(self.pay_frame_2)
        self.case_fine_pay.setGeometry(QtCore.QRect(200, 120, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.case_fine_pay.setFont(font)
        self.case_fine_pay.setObjectName("case_fine_pay")
        self.case_fine_value = QtWidgets.QLabel(self.pay_frame_2)
        self.case_fine_value.setGeometry(QtCore.QRect(10, 120, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.case_fine_value.setFont(font)
        self.case_fine_value.setAlignment(QtCore.Qt.AlignCenter)
        self.case_fine_value.setObjectName("case_fine_value")
        self.case_fine_lbl = QtWidgets.QLabel(self.pay_frame_2)
        self.case_fine_lbl.setGeometry(QtCore.QRect(10, 20, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.case_fine_lbl.setFont(font)
        self.case_fine_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.case_fine_lbl.setObjectName("case_fine_lbl")
        self.add_person = QtWidgets.QPushButton(self.form)
        self.add_person.setGeometry(QtCore.QRect(390, 30, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.add_person.setFont(font)
        self.add_person.setObjectName("add_person")
        self.choose_case_lbl = QtWidgets.QLabel(self.form)
        self.choose_case_lbl.setGeometry(QtCore.QRect(10, 70, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.choose_case_lbl.setFont(font)
        self.choose_case_lbl.setObjectName("choose_case_lbl")
        self.delete_person = QtWidgets.QPushButton(self.form)
        self.delete_person.setGeometry(QtCore.QRect(390, 50, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.delete_person.setFont(font)
        self.delete_person.setObjectName("delete_person")
        self.back = QtWidgets.QPushButton(self.form)
        self.back.setGeometry(QtCore.QRect(20, 560, 121, 31))
        self.back.setObjectName("back")
        self.del_acc = QtWidgets.QPushButton(self.form)
        self.del_acc.setGeometry(QtCore.QRect(170, 560, 121, 31))
        self.del_acc.setObjectName("del_acc")
        self.frame = QtWidgets.QFrame(self.form)
        self.frame.setGeometry(QtCore.QRect(430, 410, 361, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.find_complaint = QtWidgets.QPushButton(self.frame)
        self.find_complaint.setGeometry(QtCore.QRect(190, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.find_complaint.setFont(font)
        self.find_complaint.setObjectName("find_complaint")
        self.complain = QtWidgets.QPushButton(self.frame)
        self.complain.setGeometry(QtCore.QRect(10, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.complain.setFont(font)
        self.complain.setObjectName("complain")
        self.comp_message = QtWidgets.QLabel(self.frame)
        self.comp_message.setGeometry(QtCore.QRect(10, 100, 341, 21))
        self.comp_message.setText("")
        self.comp_message.setAlignment(QtCore.Qt.AlignCenter)
        self.comp_message.setObjectName("comp_message")
        CasePay.setCentralWidget(self.form)

        self.retranslateUi(CasePay)
        QtCore.QMetaObject.connectSlotsByName(CasePay)

    def retranslateUi(self, CasePay):
        _translate = QtCore.QCoreApplication.translate
        CasePay.setWindowTitle(_translate("CasePay", "Case pay"))
        self.choose_person_lbl.setText(_translate("CasePay", "Выберите водителя:"))
        self.sum_fine_lbl.setText(_translate("CasePay", "Общая сумма штрафов к оплате"))
        self.sum_fine_value.setText(_translate("CasePay", "0"))
        self.sum_fine_pay.setText(_translate("CasePay", "Оплатить"))
        self.case_fine_pay.setText(_translate("CasePay", "Оплатить"))
        self.case_fine_value.setText(_translate("CasePay", "0"))
        self.case_fine_lbl.setText(_translate("CasePay", "Штраф за нарушение"))
        self.add_person.setText(_translate("CasePay", "+"))
        self.choose_case_lbl.setText(_translate("CasePay", "Выберите дело:"))
        self.delete_person.setText(_translate("CasePay", "-"))
        self.back.setText(_translate("CasePay", "Назад в меню"))
        self.del_acc.setText(_translate("CasePay", "Удалить аккаунт"))
        self.find_complaint.setText(_translate("CasePay", "Найти аппеляцию"))
        self.complain.setText(_translate("CasePay", "Подать аппеляцию"))
