# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_article.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeArticle(object):
    def setupUi(self, ChangeArticle):
        ChangeArticle.setObjectName("ChangeArticle")
        ChangeArticle.resize(654, 267)
        ChangeArticle.setStyleSheet("\n"
"#form{\n"
"background:url(img/pbg4.jpg)\n"
"}\n"
"QTextEdit{\n"
"color:white;\n"
"}\n"
"#fine_lbl{\n"
"background-color: transparent;\n"
"color:white;\n"
"}\n"
"#article_lbl{\n"
"background-color: transparent;\n"
"color:white;\n"
"}\n"
"#loose_lbl{\n"
"background-color: transparent;\n"
"color:white;\n"
"}\n"
"QLineEdit{\n"
"background:transparent;\n"
"border:2px solid #2312ff;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"QLineEdit:focus{\n"
"background:transparent;\n"
"border:2px solid red;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"QFrame{\n"
"background: rgba(0,0,0,0.7);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QComboBox{\n"
"border:1px solid #2312ff;\n"
"border-radius:4px;\n"
"padding-left: 10px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"}\n"
"QComboBox:on{\n"
"border:2px solid #2312ff;\n"
"}\n"
"QComboBox QListView{\n"
"font-size:12px;\n"
"border: 1px solid rgba(0,0,0,10%);\n"
"padding: 5px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"outline:0px;\n"
"}\n"
"QComboBox QListView::item{\n"
"pading-left:10px;\n"
"background-color:rgba(0,0,0,0.7);\n"
"}\n"
"QComboBox QListView::item:hover{\n"
"background-color:#1e90ff;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"background-color:#1e90ff;\n"
"}\n"
"QPushButton{\n"
"border-radius:15px;\n"
"color:white;\n"
"border:2px solid #2312ff;\n"
"background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#show_password{\n"
"border-radius:8px;\n"
"background:grey;\n"
"color:white;\n"
"}\n"
"#show_password:hover{\n"
"border-radius:8px;\n"
"border: 1px solid red;\n"
"color:white;\n"
"background:grey;\n"
"}\n"
"QComboBox{\n"
"border:1px solid #2312ff;\n"
"border-radius:4px;\n"
"padding-left: 10px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"}\n"
"QComboBox:on{\n"
"border:2px solid #2312ff;\n"
"}\n"
"QComboBox QListView{\n"
"font-size:12px;\n"
"border: 1px solid rgba(0,0,0,10%);\n"
"padding: 5px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"outline:0px;\n"
"}\n"
"QComboBox QListView::item{\n"
"pading-left:10px;\n"
"background-color:rgba(0,0,0,0.7);\n"
"}\n"
"QComboBox QListView::item:hover{\n"
"background-color:#1e90ff;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"background-color:#1e90ff;\n"
"}")
        self.form = QtWidgets.QWidget(ChangeArticle)
        self.form.setObjectName("form")
        self.article = QtWidgets.QComboBox(self.form)
        self.article.setGeometry(QtCore.QRect(10, 50, 291, 22))
        self.article.setObjectName("article")
        self.article_lbl = QtWidgets.QLabel(self.form)
        self.article_lbl.setGeometry(QtCore.QRect(10, 20, 301, 16))
        self.article_lbl.setObjectName("article_lbl")
        self.fine_lbl = QtWidgets.QLabel(self.form)
        self.fine_lbl.setGeometry(QtCore.QRect(10, 100, 301, 16))
        self.fine_lbl.setObjectName("fine_lbl")
        self.loose_lbl = QtWidgets.QLabel(self.form)
        self.loose_lbl.setGeometry(QtCore.QRect(10, 180, 301, 16))
        self.loose_lbl.setObjectName("loose_lbl")
        self.output = QtWidgets.QTextEdit(self.form)
        self.output.setGeometry(QtCore.QRect(320, 50, 321, 171))
        self.output.setObjectName("output")
        self.submit = QtWidgets.QPushButton(self.form)
        self.submit.setGeometry(QtCore.QRect(440, 230, 91, 31))
        self.submit.setObjectName("submit")
        self.fine = QtWidgets.QLineEdit(self.form)
        self.fine.setGeometry(QtCore.QRect(10, 130, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.fine.setFont(font)
        self.fine.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.fine.setAlignment(QtCore.Qt.AlignCenter)
        self.fine.setObjectName("fine")
        self.loose = QtWidgets.QLineEdit(self.form)
        self.loose.setGeometry(QtCore.QRect(10, 210, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.loose.setFont(font)
        self.loose.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.loose.setAlignment(QtCore.Qt.AlignCenter)
        self.loose.setObjectName("loose")
        ChangeArticle.setCentralWidget(self.form)

        self.retranslateUi(ChangeArticle)
        QtCore.QMetaObject.connectSlotsByName(ChangeArticle)

    def retranslateUi(self, ChangeArticle):
        _translate = QtCore.QCoreApplication.translate
        ChangeArticle.setWindowTitle(_translate("ChangeArticle", "Изменить статью"))
        self.article_lbl.setText(_translate("ChangeArticle", "Выберите статью:"))
        self.fine_lbl.setText(_translate("ChangeArticle", "Штраф"))
        self.loose_lbl.setText(_translate("ChangeArticle", "Лишение прав"))
        self.output.setPlaceholderText(_translate("ChangeArticle", "....."))
        self.submit.setText(_translate("ChangeArticle", "Добавить"))
        self.fine.setPlaceholderText(_translate("ChangeArticle", "..."))
        self.loose.setPlaceholderText(_translate("ChangeArticle", "..."))
