# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'complaint.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Complaint(object):
    def setupUi(self, Complaint):
        Complaint.setObjectName("Complaint")
        Complaint.resize(800, 600)
        Complaint.setStyleSheet("#form{\n"
"background:url(img/pbg4.jpg)\n"
"}\n"
"QCheckBox{\n"
"color:white\n"
"}\n"
"QFrame{\n"
"background: rgba(0,0,0,0.7);\n"
"border-radius:15px;\n"
"}\n"
"QTextEdit{\n"
"background: rgba(0,0,0,0.5);\n"
"border-radius:15px;\n"
"border: 2px solid blue;\n"
"color:white\n"
"}\n"
"QLineEdit{\n"
"background:transparent;\n"
"border:2px solid #2312ff;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"QLineEdit:focus{\n"
"background:transparent;\n"
"border:2px solid red;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"QPushButton{\n"
"border-radius:15px;\n"
"color:white;\n"
"border:2px solid #2312ff;\n"
"background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"QLabel{\n"
"color:white;\n"
"background:transparent;\n"
"\n"
"}")
        self.form = QtWidgets.QWidget(Complaint)
        self.form.setObjectName("form")
        self.frame = QtWidgets.QFrame(self.form)
        self.frame.setGeometry(QtCore.QRect(20, 20, 771, 561))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.passport = QtWidgets.QLineEdit(self.frame)
        self.passport.setGeometry(QtCore.QRect(30, 60, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.passport.setFont(font)
        self.passport.setAlignment(QtCore.Qt.AlignCenter)
        self.passport.setObjectName("passport")
        self.passport_lbl = QtWidgets.QLabel(self.frame)
        self.passport_lbl.setGeometry(QtCore.QRect(320, 60, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.passport_lbl.setFont(font)
        self.passport_lbl.setObjectName("passport_lbl")
        self.driver_lisence_lbl = QtWidgets.QLabel(self.frame)
        self.driver_lisence_lbl.setGeometry(QtCore.QRect(320, 120, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.driver_lisence_lbl.setFont(font)
        self.driver_lisence_lbl.setObjectName("driver_lisence_lbl")
        self.send_complaint = QtWidgets.QPushButton(self.frame)
        self.send_complaint.setGeometry(QtCore.QRect(420, 440, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.send_complaint.setFont(font)
        self.send_complaint.setObjectName("send_complaint")
        self.was_a_driver = QtWidgets.QCheckBox(self.frame)
        self.was_a_driver.setGeometry(QtCore.QRect(100, 120, 70, 17))
        self.was_a_driver.setObjectName("was_a_driver")
        self.full_justification = QtWidgets.QCheckBox(self.frame)
        self.full_justification.setGeometry(QtCore.QRect(100, 170, 70, 17))
        self.full_justification.setObjectName("full_justification")
        self.driver_lisence_lbl_2 = QtWidgets.QLabel(self.frame)
        self.driver_lisence_lbl_2.setGeometry(QtCore.QRect(320, 160, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.driver_lisence_lbl_2.setFont(font)
        self.driver_lisence_lbl_2.setObjectName("driver_lisence_lbl_2")
        self.comment = QtWidgets.QTextEdit(self.frame)
        self.comment.setGeometry(QtCore.QRect(40, 210, 461, 221))
        self.comment.setObjectName("comment")
        self.driver_lisence_lbl_3 = QtWidgets.QLabel(self.frame)
        self.driver_lisence_lbl_3.setGeometry(QtCore.QRect(510, 300, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.driver_lisence_lbl_3.setFont(font)
        self.driver_lisence_lbl_3.setObjectName("driver_lisence_lbl_3")
        Complaint.setCentralWidget(self.form)

        self.retranslateUi(Complaint)
        QtCore.QMetaObject.connectSlotsByName(Complaint)

    def retranslateUi(self, Complaint):
        _translate = QtCore.QCoreApplication.translate
        Complaint.setWindowTitle(_translate("Complaint", "Complaint"))
        self.passport_lbl.setText(_translate("Complaint", "Серия и номер паспорта"))
        self.driver_lisence_lbl.setText(_translate("Complaint", "Были ли вы водителем во время возбуждения дела?"))
        self.send_complaint.setText(_translate("Complaint", "Создать жалобу"))
        self.was_a_driver.setText(_translate("Complaint", "Да"))
        self.full_justification.setText(_translate("Complaint", "Да"))
        self.driver_lisence_lbl_2.setText(_translate("Complaint", "Хотите ли вы быть полностью оправданы?"))
        self.comment.setPlaceholderText(_translate("Complaint", "Обязательно для заполнения"))
        self.driver_lisence_lbl_3.setText(_translate("Complaint", "Ваш комментарий"))
