# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Confirm(object):
    def setupUi(self, Confirm):
        Confirm.setObjectName("Confirm")
        Confirm.resize(531, 260)
        Confirm.setStyleSheet("\n"
"#form{\n"
"background:url(img/pbg4.jpg)\n"
"}\n"
"QLabel{\n"
"color:white\n"
"}\n"
"QLineEdit{\n"
"background:transparent;\n"
"border:2px solid #2312ff;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"QLineEdit:focus{\n"
"background:transparent;\n"
"border:2px solid red;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"QFrame{\n"
"background: rgba(0,0,0,0.7);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QComboBox{\n"
"border:1px solid #2312ff;\n"
"border-radius:4px;\n"
"padding-left: 10px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"}\n"
"QComboBox:on{\n"
"border:2px solid #2312ff;\n"
"}\n"
"QComboBox QListView{\n"
"font-size:12px;\n"
"border: 1px solid rgba(0,0,0,10%);\n"
"padding: 5px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"outline:0px;\n"
"}\n"
"QComboBox QListView::item{\n"
"pading-left:10px;\n"
"background-color:rgba(0,0,0,0.7);\n"
"}\n"
"QComboBox QListView::item:hover{\n"
"background-color:#1e90ff;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"background-color:#1e90ff;\n"
"}\n"
"QPushButton{\n"
"border-radius:15px;\n"
"color:white;\n"
"border:2px solid #2312ff;\n"
"background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#show_password{\n"
"border-radius:8px;\n"
"background:grey;\n"
"color:white;\n"
"}\n"
"#show_password:hover{\n"
"border-radius:8px;\n"
"border: 1px solid red;\n"
"color:white;\n"
"background:grey;\n"
"}\n"
"")
        self.form = QtWidgets.QWidget(Confirm)
        self.form.setObjectName("form")
        self.frame = QtWidgets.QFrame(self.form)
        self.frame.setGeometry(QtCore.QRect(30, 50, 471, 161))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.delete_acc = QtWidgets.QPushButton(self.frame)
        self.delete_acc.setGeometry(QtCore.QRect(160, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.delete_acc.setFont(font)
        self.delete_acc.setObjectName("delete_acc")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(80, 20, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.password.setFont(font)
        self.password.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.show_password = QtWidgets.QPushButton(self.frame)
        self.show_password.setGeometry(QtCore.QRect(380, 30, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.show_password.setFont(font)
        self.show_password.setText("")
        self.show_password.setObjectName("show_password")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 140, 461, 20))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        Confirm.setCentralWidget(self.form)

        self.retranslateUi(Confirm)
        QtCore.QMetaObject.connectSlotsByName(Confirm)

    def retranslateUi(self, Confirm):
        _translate = QtCore.QCoreApplication.translate
        Confirm.setWindowTitle(_translate("Confirm", "Подтверждение"))
        self.delete_acc.setText(_translate("Confirm", "Удалить аккаунт"))
        self.password.setPlaceholderText(_translate("Confirm", "Пароль"))
