# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_driver.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteDriver(object):
    def setupUi(self, DeleteDriver):
        DeleteDriver.setObjectName("DeleteDriver")
        DeleteDriver.resize(613, 244)
        DeleteDriver.setLayoutDirection(QtCore.Qt.LeftToRight)
        DeleteDriver.setStyleSheet("\n"
"#form{\n"
"background:url(img/pbg4.jpg)\n"
"}\n"
"\n"
"QFrame{\n"
"background: rgba(0,0,0,0.7);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QComboBox{\n"
"border:1px solid #2312ff;\n"
"border-radius:4px;\n"
"padding-left: 10px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"}\n"
"QComboBox:on{\n"
"border:2px solid #2312ff;\n"
"}\n"
"QComboBox QListView{\n"
"font-size:12px;\n"
"border: 1px solid rgba(0,0,0,10%);\n"
"padding: 5px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"outline:0px;\n"
"}\n"
"QComboBox QListView::item{\n"
"pading-left:10px;\n"
"background-color:rgba(0,0,0,0.7);\n"
"}\n"
"QComboBox QListView::item:hover{\n"
"background-color:#1e90ff;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"background-color:#1e90ff;\n"
"}\n"
"QPushButton{\n"
"border-radius:15px;\n"
"color:white;\n"
"border:2px solid #2312ff;\n"
"background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"")
        self.form = QtWidgets.QWidget(DeleteDriver)
        self.form.setObjectName("form")
        self.frame = QtWidgets.QFrame(self.form)
        self.frame.setGeometry(QtCore.QRect(60, 40, 491, 171))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.cb_drivers = QtWidgets.QComboBox(self.frame)
        self.cb_drivers.setGeometry(QtCore.QRect(10, 10, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.cb_drivers.setFont(font)
        self.cb_drivers.setObjectName("cb_drivers")
        self.delete_driver_btn = QtWidgets.QPushButton(self.frame)
        self.delete_driver_btn.setGeometry(QtCore.QRect(130, 90, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.delete_driver_btn.setFont(font)
        self.delete_driver_btn.setObjectName("delete_driver_btn")
        DeleteDriver.setCentralWidget(self.form)

        self.retranslateUi(DeleteDriver)
        QtCore.QMetaObject.connectSlotsByName(DeleteDriver)

    def retranslateUi(self, DeleteDriver):
        _translate = QtCore.QCoreApplication.translate
        DeleteDriver.setWindowTitle(_translate("DeleteDriver", "Delete driver"))
        self.delete_driver_btn.setText(_translate("DeleteDriver", "Удалить водителя"))
