# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'find_protocol.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FindComplaint(object):
    def setupUi(self, FindComplaint):
        FindComplaint.setObjectName("FindComplaint")
        FindComplaint.resize(836, 667)
        FindComplaint.setStyleSheet("\n"
"#form{\n"
"background:url(img/pbg4.jpg)\n"
"}\n"
"#label_2{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"#message{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"#driver_lisence_lbl_2{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"#driver_passport_lbl_3{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"#driver_passport_lbl_2{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"QTextEdit{\n"
"color:white;\n"
"\n"
"}\n"
"#fine_lbl{\n"
"background-color: transparent;\n"
"color:white;\n"
"}\n"
"#article_lbl{\n"
"background-color: transparent;\n"
"color:white;\n"
"}\n"
"#loose_lbl{\n"
"background-color: transparent;\n"
"color:white;\n"
"}\n"
"QLineEdit{\n"
"background:transparent;\n"
"border:2px solid #2312ff;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"QLineEdit:focus{\n"
"background:transparent;\n"
"border:2px solid red;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"QFrame{\n"
"background: rgba(0,0,0,0.7);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QComboBox{\n"
"border:1px solid #2312ff;\n"
"border-radius:4px;\n"
"padding-left: 10px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"}\n"
"QComboBox:on{\n"
"border:2px solid #2312ff;\n"
"}\n"
"QComboBox QListView{\n"
"font-size:12px;\n"
"border: 1px solid rgba(0,0,0,10%);\n"
"padding: 5px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"outline:0px;\n"
"}\n"
"QComboBox QListView::item{\n"
"pading-left:10px;\n"
"background-color:rgba(0,0,0,0.7);\n"
"}\n"
"QComboBox QListView::item:hover{\n"
"background-color:#1e90ff;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"background-color:#1e90ff;\n"
"}\n"
"QPushButton{\n"
"border-radius:15px;\n"
"color:white;\n"
"border:2px solid #2312ff;\n"
"background:transparent;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#show_password{\n"
"border-radius:8px;\n"
"background:grey;\n"
"color:white;\n"
"}\n"
"#show_password:hover{\n"
"border-radius:8px;\n"
"border: 1px solid red;\n"
"color:white;\n"
"background:grey;\n"
"}\n"
"QComboBox{\n"
"border:1px solid #2312ff;\n"
"border-radius:4px;\n"
"padding-left: 10px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"}\n"
"QComboBox:on{\n"
"border:2px solid #2312ff;\n"
"}\n"
"QComboBox QListView{\n"
"font-size:12px;\n"
"border: 1px solid rgba(0,0,0,10%);\n"
"padding: 5px;\n"
"background:rgba(0,0,0,0.7);\n"
"color:white;\n"
"outline:0px;\n"
"}\n"
"QComboBox QListView::item{\n"
"pading-left:10px;\n"
"background-color:rgba(0,0,0,0.7);\n"
"}\n"
"QComboBox QListView::item:hover{\n"
"background-color:#1e90ff;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"background-color:#1e90ff;\n"
"}")
        self.form = QtWidgets.QWidget(FindComplaint)
        self.form.setObjectName("form")
        self.frame_output = QtWidgets.QFrame(self.form)
        self.frame_output.setGeometry(QtCore.QRect(20, 270, 801, 371))
        self.frame_output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_output.setObjectName("frame_output")
        self.output = QtWidgets.QTextEdit(self.frame_output)
        self.output.setGeometry(QtCore.QRect(10, 10, 461, 351))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.output.setFont(font)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.choose_cb = QtWidgets.QComboBox(self.frame_output)
        self.choose_cb.setGeometry(QtCore.QRect(490, 30, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.choose_cb.setFont(font)
        self.choose_cb.setObjectName("choose_cb")
        self.output_cb = QtWidgets.QTextEdit(self.frame_output)
        self.output_cb.setGeometry(QtCore.QRect(490, 60, 291, 301))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.output_cb.setFont(font)
        self.output_cb.setReadOnly(True)
        self.output_cb.setPlaceholderText("")
        self.output_cb.setObjectName("output_cb")
        self.label = QtWidgets.QLabel(self.frame_output)
        self.label.setGeometry(QtCore.QRect(490, 10, 281, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.complaint_frame = QtWidgets.QFrame(self.form)
        self.complaint_frame.setGeometry(QtCore.QRect(20, 20, 801, 231))
        self.complaint_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.complaint_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.complaint_frame.setObjectName("complaint_frame")
        self.case_id = QtWidgets.QLineEdit(self.complaint_frame)
        self.case_id.setGeometry(QtCore.QRect(10, 20, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.case_id.setFont(font)
        self.case_id.setAlignment(QtCore.Qt.AlignCenter)
        self.case_id.setObjectName("case_id")
        self.passport = QtWidgets.QLineEdit(self.complaint_frame)
        self.passport.setGeometry(QtCore.QRect(10, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.passport.setFont(font)
        self.passport.setAlignment(QtCore.Qt.AlignCenter)
        self.passport.setObjectName("passport")
        self.driver_lisence_lbl_2 = QtWidgets.QLabel(self.complaint_frame)
        self.driver_lisence_lbl_2.setGeometry(QtCore.QRect(240, 20, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.driver_lisence_lbl_2.setFont(font)
        self.driver_lisence_lbl_2.setObjectName("driver_lisence_lbl_2")
        self.driver_passport_lbl_2 = QtWidgets.QLabel(self.complaint_frame)
        self.driver_passport_lbl_2.setGeometry(QtCore.QRect(240, 70, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.driver_passport_lbl_2.setFont(font)
        self.driver_passport_lbl_2.setObjectName("driver_passport_lbl_2")
        self.submit_find_complaint = QtWidgets.QPushButton(self.complaint_frame)
        self.submit_find_complaint.setGeometry(QtCore.QRect(200, 180, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.submit_find_complaint.setFont(font)
        self.submit_find_complaint.setObjectName("submit_find_complaint")
        self.complaint_id = QtWidgets.QLineEdit(self.complaint_frame)
        self.complaint_id.setGeometry(QtCore.QRect(10, 120, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.complaint_id.setFont(font)
        self.complaint_id.setAlignment(QtCore.Qt.AlignCenter)
        self.complaint_id.setObjectName("complaint_id")
        self.driver_passport_lbl_3 = QtWidgets.QLabel(self.complaint_frame)
        self.driver_passport_lbl_3.setGeometry(QtCore.QRect(240, 120, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.driver_passport_lbl_3.setFont(font)
        self.driver_passport_lbl_3.setObjectName("driver_passport_lbl_3")
        self.delete_btn = QtWidgets.QPushButton(self.complaint_frame)
        self.delete_btn.setGeometry(QtCore.QRect(630, 90, 111, 41))
        self.delete_btn.setObjectName("delete_btn")
        self.label_2 = QtWidgets.QLabel(self.complaint_frame)
        self.label_2.setGeometry(QtCore.QRect(610, 60, 161, 20))
        self.label_2.setObjectName("label_2")
        self.message = QtWidgets.QLabel(self.complaint_frame)
        self.message.setGeometry(QtCore.QRect(510, 160, 271, 31))
        self.message.setText("")
        self.message.setObjectName("message")
        FindComplaint.setCentralWidget(self.form)

        self.retranslateUi(FindComplaint)
        QtCore.QMetaObject.connectSlotsByName(FindComplaint)

    def retranslateUi(self, FindComplaint):
        _translate = QtCore.QCoreApplication.translate
        FindComplaint.setWindowTitle(_translate("FindComplaint", "Поиск аппеляции"))
        self.output.setPlaceholderText(_translate("FindComplaint", "....."))
        self.label.setText(_translate("FindComplaint", "Найденные аппеляции:"))
        self.driver_lisence_lbl_2.setText(_translate("FindComplaint", "Номер дела"))
        self.driver_passport_lbl_2.setText(_translate("FindComplaint", "Серия и номер паспорта"))
        self.submit_find_complaint.setText(_translate("FindComplaint", "Найти"))
        self.driver_passport_lbl_3.setText(_translate("FindComplaint", "Номер аппеляции"))
        self.delete_btn.setText(_translate("FindComplaint", "Удалить"))
        self.label_2.setText(_translate("FindComplaint", "Удаление аппеляции по номеру"))
