# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(791, 595)
        Menu.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Menu.setStyleSheet("\n"
"#form{\n"
"background:url(img/pbg4.jpg)\n"
"}\n"
"\n"
"QLabel{\n"
"color: white;\n"
"}\n"
"\n"
"#forgot_password{\n"
"background:transparent;\n"
"color:white;\n"
"}\n"
"#forgot_password:hover{\n"
"border-radius:8px;\n"
"border: 1px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#show_password{\n"
"border-radius:8px;\n"
"background:grey;\n"
"color:white;\n"
"}\n"
"#show_password:hover{\n"
"border-radius:8px;\n"
"border: 1px solid red;\n"
"color:white;\n"
"background:grey;\n"
"}\n"
"\n"
"#back{\n"
"background:transparent;\n"
"border-radius:8px;\n"
"border: 1px solid white;\n"
"color:white;\n"
"}\n"
"#back:hover{\n"
"background:transparent;\n"
"border-radius:8px;\n"
"border: 1px solid red;\n"
"color:white;\n"
"}\n"
"\n"
"#registration{\n"
"background:transparent;\n"
"color:white;\n"
"}\n"
"#registration:hover{\n"
"border-radius:8px;\n"
"border: 1px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"\n"
"#enter_background{\n"
"background: rgba(0,0,0,0.7);\n"
"border-radius:15px;\n"
"}\n"
"#registration_frame{\n"
"background: rgba(0,0,0,0.7);\n"
"border-radius:15px;\n"
"}\n"
"#icon{\n"
"background:#2312ff;\n"
"border-radius: 60px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background:transparent;\n"
"border:2px solid #2312ff;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"QLineEdit:focus{\n"
"background:transparent;\n"
"border:2px solid red;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"#enter{\n"
"border-radius:15px;\n"
"color:white;\n"
"border:2px solid #2312ff;\n"
"background:transparent;\n"
"}\n"
"#enter:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#title{\n"
"color:white;\n"
"border:4px solid blue;\n"
"border-radius:15px;\n"
"}\n"
"#employee{\n"
"background:transparent;\n"
"border:2px solid #2312ff;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"#citizen{\n"
"background:transparent;\n"
"border:2px solid#2312ff;\n"
"border-radius:15px;\n"
"color:white;\n"
"}\n"
"#employee:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#citizen:hover{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#employee:disabled{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"#citizen:disabled{\n"
"border-radius:15px;\n"
"border:2px solid red;\n"
"color:white;\n"
"background: transparent;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.form = QtWidgets.QWidget(Menu)
        self.form.setObjectName("form")
        self.title = QtWidgets.QLabel(self.form)
        self.title.setGeometry(QtCore.QRect(10, 9, 771, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(22)
        self.title.setFont(font)
        self.title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.title.setLineWidth(20)
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setScaledContents(False)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.enter_background = QtWidgets.QFrame(self.form)
        self.enter_background.setGeometry(QtCore.QRect(200, 170, 371, 381))
        self.enter_background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.enter_background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.enter_background.setObjectName("enter_background")
        self.password_line = QtWidgets.QLineEdit(self.enter_background)
        self.password_line.setGeometry(QtCore.QRect(20, 210, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.password_line.setFont(font)
        self.password_line.setText("")
        self.password_line.setMaxLength(20)
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setAlignment(QtCore.Qt.AlignCenter)
        self.password_line.setObjectName("password_line")
        self.login_line = QtWidgets.QLineEdit(self.enter_background)
        self.login_line.setGeometry(QtCore.QRect(20, 160, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.login_line.setFont(font)
        self.login_line.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.login_line.setAlignment(QtCore.Qt.AlignCenter)
        self.login_line.setObjectName("login_line")
        self.enter = QtWidgets.QPushButton(self.enter_background)
        self.enter.setGeometry(QtCore.QRect(110, 310, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.enter.setFont(font)
        self.enter.setObjectName("enter")
        self.employee = QtWidgets.QPushButton(self.enter_background)
        self.employee.setGeometry(QtCore.QRect(10, 30, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.employee.setFont(font)
        self.employee.setObjectName("employee")
        self.citizen = QtWidgets.QPushButton(self.enter_background)
        self.citizen.setEnabled(True)
        self.citizen.setGeometry(QtCore.QRect(240, 30, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.citizen.setFont(font)
        self.citizen.setObjectName("citizen")
        self.forgot_password = QtWidgets.QPushButton(self.enter_background)
        self.forgot_password.setGeometry(QtCore.QRect(120, 260, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.forgot_password.setFont(font)
        self.forgot_password.setObjectName("forgot_password")
        self.registration = QtWidgets.QPushButton(self.enter_background)
        self.registration.setGeometry(QtCore.QRect(20, 260, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.registration.setFont(font)
        self.registration.setObjectName("registration")
        self.back = QtWidgets.QPushButton(self.enter_background)
        self.back.setGeometry(QtCore.QRect(20, 320, 71, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.show_password = QtWidgets.QPushButton(self.enter_background)
        self.show_password.setGeometry(QtCore.QRect(320, 220, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.show_password.setFont(font)
        self.show_password.setText("")
        self.show_password.setObjectName("show_password")
        self.username = QtWidgets.QLineEdit(self.enter_background)
        self.username.setGeometry(QtCore.QRect(20, 60, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.username.setFont(font)
        self.username.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setObjectName("username")
        self.phone = QtWidgets.QLineEdit(self.enter_background)
        self.phone.setGeometry(QtCore.QRect(20, 110, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.phone.setFont(font)
        self.phone.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.phone.setAlignment(QtCore.Qt.AlignCenter)
        self.phone.setObjectName("phone")
        self.message = QtWidgets.QLabel(self.enter_background)
        self.message.setGeometry(QtCore.QRect(20, 360, 341, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.message.setFont(font)
        self.message.setText("")
        self.message.setAlignment(QtCore.Qt.AlignCenter)
        self.message.setObjectName("message")
        self.icon = QtWidgets.QToolButton(self.form)
        self.icon.setGeometry(QtCore.QRect(320, 90, 131, 121))
        self.icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon.setIcon(icon)
        self.icon.setIconSize(QtCore.QSize(80, 80))
        self.icon.setObjectName("icon")
        Menu.setCentralWidget(self.form)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Traffic Police"))
        self.title.setText(_translate("Menu", "Traffic Police App"))
        self.password_line.setPlaceholderText(_translate("Menu", "Пароль"))
        self.login_line.setPlaceholderText(_translate("Menu", "Email"))
        self.enter.setText(_translate("Menu", "Войти"))
        self.employee.setText(_translate("Menu", "для служащих"))
        self.citizen.setText(_translate("Menu", "для граждан"))
        self.forgot_password.setText(_translate("Menu", "Забыли пароль?"))
        self.registration.setText(_translate("Menu", "Регистрация"))
        self.back.setText(_translate("Menu", "Назад"))
        self.username.setPlaceholderText(_translate("Menu", "Имя пользователя"))
        self.phone.setPlaceholderText(_translate("Menu", "Номер телефона"))
